apiVersion: v2
name: sharedidp
description: Helm chart for Catena-X Shared Keycloak Instance
type: application
version: 0.5.1
dependencies:
  - name: keycloak
    repository: https://charts.bitnami.com/bitnami
    version: 7.1.18
