keycloak:
  extraVolumes:
    - name: themes
      emptyDir: {}
    - name: realms
      emptyDir: {}
    - name: realm-secrets
      secret:
        secretName: secret-sharedidp-realms
  extraVolumeMounts:
    - name: themes
      mountPath: "/opt/bitnami/keycloak/themes/catenax-shared"
    - name: realms
      mountPath: "/realms"
    - name: realm-secrets
      mountPath: "/secrets"
  initContainers:
    - name: import
      image: ghcr.io/catenax-ng/product-portal-iam_iam-import-pre-prod:latest
      imagePullPolicy: Always
      command:
        - sh
      args:
        - -c
        - |
          echo "Copying themes..."
          cp -R /import/themes/catenax-shared/* /themes
          echo "Copying realms..."
          cp -R /import/catenax-shared/realms/* /realms
          echo "Copying realms-secrets..."
          cp /secrets/* /realms
      volumeMounts:
      - name: themes
        mountPath: "/themes"
      - name: realms
        mountPath: "/realms"
      - name: realm-secrets
        mountPath: "/secrets"
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: sharedidp.pre-prod.demo.catena-x.net
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
      nginx.ingress.kubernetes.io/cors-allow-methods: PUT, GET, POST, OPTIONS
      nginx.ingress.kubernetes.io/cors-allow-origin: https://sharedidp.pre-prod.demo.catena-x.net, http://localhost:3000
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
      nginx.ingress.kubernetes.io/proxy-buffering: "on"
      nginx.ingress.kubernetes.io/proxy-buffers-number: "20"
      nginx.ingress.kubernetes.io/use-regex: "true"
    tls: true

secrets:
  auth:
    existingSecret:
      adminpassword: "<path:portal/data/pre-prod/iam/sharedidp-keycloak#admin-password>"
      managementpassword: "<path:portal/data/pre-prod/iam/sharedidp-keycloak#management-password>"
  postgresql:
    auth:
      existingSecret:
        postgrespassword: "<path:portal/data/pre-prod/iam/sharedidp-postgres#postgres-password>"
        password: "<path:portal/data/pre-prod/iam/sharedidp-postgres#password>"
        replicationPassword: "<path:portal/data/pre-prod/iam/sharedidp-postgres#replication-password>"
  realmuser:
    enabled: true
    cxtestaccessuser: "<path:portal/data/pre-prod/iam/sharedidp-realms#CX-Test-Access-users-0.json>"
    company1user: "<path:portal/data/pre-prod/iam/sharedidp-realms#Company-1-users-0.json>"
    company2user: "<path:portal/data/pre-prod/iam/sharedidp-realms#Company-2-users-0.json>"
    company3user: "<path:portal/data/pre-prod/iam/sharedidp-realms#Company-3-users-0.json>"
    masteruser: "<path:portal/data/pre-prod/iam/sharedidp-realms#Company-1-users-0.json>"
