apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: {{ .Values.extraVolumeSecretPath }}
  name: secret-sharedidp-realms
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  master-realm-users-0.json: <master-realm-users-0.json>
  CX-Test-Access-users-0.json: <CX-Test-Access-users-0.json>