name: IAM-DEV

on: 
  push:
    paths:
      # this workflow file
      - '.github/workflows/cx-iam-dev.yml'
      # Docker files
      - 'docker/Dockerfile-dev.import'
      # keycloak-themes
      - 'import/keycloak-themes/**'
      # keycloak-realms
      - 'import/realm-config/dev/**'

    branches:
     - 'main'
  workflow_dispatch:

jobs:
  build:
    # name of the job starts with a "run-level" subordinate to the workflow such that we can
    # depend on them in order to implement workflow dependencies
    name: 90 iam-import image built
    runs-on: ubuntu-latest
    # rely on the first job
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}_iam-import-dev

    steps:
      # Get the latest sources
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push KeyCloak custom images for central and shared idp instances
      - name: 'Build and push KeyCloak images'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile-dev.import
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
