apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sharedidp
spec:
  destination:
    namespace: product-portal
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/sharedidp
    repoURL: 'https://github.com/catenax-ng/product-portal-iam.git'
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin-helm-args
      env:
        - name: AVP_SECRET
          value: vault-secret
        - name: helm_args
          value: '-f values.yaml -f values-beta.yaml'
  project: project-portal